### ISSUE TITLE
Mark this repository & package as deprecated

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io-modules/etcher-image-write#104]
- [ ] Add deprecation notice to README
- [ ] Archive repository
- [ ] Deprecate npm package

Ref #103

**Comment by lefuturiste** [comment]
:up:

**Comment by StoneSet** [comment]
🆙

**Comment by pyr0ball** [comment]
is there an updated package to replace this?

**Comment by StoneSet** [comment]
the sdk ?

**Comment by lurch** [comment]
ping @zvin @thundron

**Comment by zvin** [comment]
@pyr0ball @StoneSet [etcher-sdk](https://github.com/balena-io-modules/etcher-sdk), you can see an example here: https://github.com/balena-io-modules/etcher-sdk/blob/master/examples/multi-destination.ts

**Comment by oganexon** [comment]
Hi, I know this library is out of date and it would be better to use etcher-sdk.
But I get lost with the documentation, it is automatically generated with typedoc and there are no comments and the examples are not very clear.
Is it possible to have a sample code to do the equivalent of the README ?

```javascript
var emitter = imageWrite.write({
  fd: fs.openSync('/dev/rdisk2', 'rs+'), // '\\\\.\\PHYSICALDRIVE1' in Windows, for example.
  device: '/dev/rdisk2',
  size: 2014314496
}, {
  stream: fs.createReadStream('my/image'),
  size: fs.statSync('my/image').size
}, {
  check: true
});
```

Apart from that, `etcher-sdk` is much bigger than `etcher-image-write`, there are many more dependencies because there are more features.
I'm just looking to write raw data to a disk and `etcher-sdk' increases the size of my library significantly. Are there alternative packages?

**Comment by lefuturiste** [comment]
@oganexon  you can look here: https://github.com/retrobox/desktop/blob/b7a0589eb323ac499aef6bdfab1a20ecc441fe27/src/renderer/components/Installation.vue#L603 This is an example of a working usage for a desktop electron app. To write .img image file to a disk.
